#!/bin/bash
WGET=/usr/bin/wget
LIBREOFFICE=/usr/bin/libreoffice

TMPDIR="$(mktemp --directory)"

${WGET} --directory-prefix ${TMPDIR} "${1}"
${LIBREOFFICE} --headless --outdir "${TMPDIR}" -convert-to html ${TMPDIR}/*

cat "${TMPDIR}/*.html"
