#!/bin/bash
WGET=/usr/bin/wget
LIBREOFFICE=/usr/bin/libreoffice

TMPDIR="$(mktemp --directory)"

${WGET} --directory-prefix ${TMPDIR} "${1}"
${LIBREOFFICE} --headless -convert-to html --outdir "${TMPDIR}" "${TMPDIR}/*"

cat "${TMPDIR}/*.html"
